### ISSUE TITLE
undefined local variable or method `options' for #<Sidekiq::Manager>

### ISSUE THREAD

**Issue by evgeniradev** [deanpcmad/sidekiq-limit_fetch#127]
Hi there,

I am using 'sidekiq' and 'sidekiq-limit_fetch' on:

Ruby: '3.1.2'
Rails: '7.0.3'
sidekiq: '6.5.0'
sidekiq-limit_fetch: '4.1.0'

I am getting the below error when running: 'bundle exec sidekiq'

```
 undefined local variable or method `options' for #<Sidekiq::Manager...

      Sidekiq::LimitFetch::Queues.start options
                                        ^^^^^^^
2022-06-08T17:05:32.508Z pid=96004 tid=1xro WARN: /Users/home/.rvm/gems/ruby-3.1.2/gems/sidekiq-limit_fetch-4.1.0/lib/sidekiq/extensions/manager.rb:9:in `start'
/Users/home/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.0/lib/sidekiq/launcher.rb:36:in `run'
/Users/home/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.0/lib/sidekiq/cli.rb:121:in `launch'
/Users/home/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.0/lib/sidekiq/cli.rb:110:in `run'
/Users/home/.rvm/gems/ruby-3.1.2/gems/sidekiq-6.5.0/bin/sidekiq:31:in `<top (required)>'
/Users/home/.rvm/gems/ruby-3.1.2/bin/sidekiq:25:in `load'
/Users/home/.rvm/gems/ruby-3.1.2/bin/sidekiq:25:in `<main>'
/Users/home/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `eval'
/Users/home/.rvm/gems/ruby-3.1.2/bin/ruby_executable_hooks:22:in `<main>'
```

Could you let me know if this is an issue with the library please?

**Comment by evgeniradev** [comment]
@denisj I implemented a fix here https://github.com/evgeniradev/sidekiq-limit_fetch/tree/fix_undefined_var_options

See if it works for you. It seems to be working for me. I also raised a PR with @deanpcmad in cause they are happy to merge it with the master branch.

**Comment by deanpcmad** [comment]
Odd, I didn't get an email notification about this issue yesterday. Will try test the PR and release tonight :)

**Comment by deanpcmad** [comment]
v4.2.0 has now been released 😄
